[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# name = "OGRaySpY"
authors = [{name = "M. F. MÃ¡duar", email = "maduar@vivaldi.net"}]
dynamic = ["version", "description"]